/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bkc_android_mdxplayer_PCMRender */

#ifndef _Included_com_bkc_android_mdxplayer_PCMRender
#define _Included_com_bkc_android_mdxplayer_PCMRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_setrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1setrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_setpcmdir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1setpcmdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_render
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1render
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_title
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1title
  (JNIEnv *, jobject);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1length
  (JNIEnv *, jobject);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_dofade
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1dofade
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_isfaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1isfaded
  (JNIEnv *, jobject);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_num_tracks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1num_1tracks
  (JNIEnv *, jobject);

/*
 * Class:     com_bkc_android_mdxplayer_PCMRender
 * Method:    sdrv_get_note
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_bkc_android_mdxplayer_PCMRender_sdrv_1get_1note
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
